<?php
/**
 * WARNING!!
 *
 * Do not modify the content of this file, it's generated by the command:
 * "php artisan models:generate" (package "axn/laravel-models-generator").
 *
 * If you want to add or modify a relation, do it in the model class or in
 * another trait.
 */
namespace App\Models\GeneratedRelations;

trait DeviceRelations
{
    
    /**
     * "has many" relation to `connection_logs` table
     * via `device_id` field.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function connectionLogs()
    {
        return $this->hasMany(\App\Models\ConnectionLog::class, 'device_id');
    }

}
