<?php
/**
 * WARNING!!
 *
 * Do not modify the content of this file, it's generated by the command:
 * "php artisan models:generate" (package "axn/laravel-models-generator").
 *
 * If you want to add or modify a relation, do it in the model class or in
 * another trait.
 */
namespace App\Models\GeneratedRelations;

trait StockLogRelations
{
    
    /**
     * "belongs to" relation to `users` table
     * via `cashier_user_id` field.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function cashierUser()
    {
        return $this->belongsTo(\App\Models\User::class, 'cashier_user_id');
    }

    /**
     * "belongs to" relation to `event_products` table
     * via `event_product_id` field.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function eventProduct()
    {
        return $this->belongsTo(\App\Models\EventProduct::class, 'event_product_id');
    }

    /**
     * "belongs to" relation to `users` table
     * via `stock_user_id` field.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function stockUser()
    {
        return $this->belongsTo(\App\Models\User::class, 'stock_user_id');
    }

}
