<?php
/**
 * WARNING!!
 *
 * Do not modify the content of this file, it's generated by the command:
 * "php artisan models:generate" (package "axn/laravel-models-generator").
 *
 * If you want to add or modify a relation, do it in the model class or in
 * another trait.
 */
namespace App\Models\GeneratedRelations;

trait UserRoleRelations
{
    
    /**
     * "belongs to" relation to `roles` table
     * via `role_id` field.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function role()
    {
        return $this->belongsTo(\App\Models\Role::class, 'role_id');
    }

    /**
     * "belongs to" relation to `users` table
     * via `user_id` field.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(\App\Models\User::class, 'user_id');
    }

}
