<?php
/**
 * WARNING!!
 *
 * Do not modify the content of this file, it's generated by the command:
 * "php artisan models:generate" (package "axn/laravel-models-generator").
 *
 * If you want to add or modify a relation, do it in the model class or in
 * another trait.
 */
namespace App\Models\GeneratedRelations;

trait UserRelations
{
    
    /**
     * "has many" relation to `events` table
     * via `user_id` field.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function events()
    {
        return $this->hasMany(\App\Models\Event::class, 'user_id');
    }

    /**
     * "has many" relation to `tickets` table
     * via `user_id` field.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function tickets()
    {
        return $this->hasMany(\App\Models\Ticket::class, 'user_id');
    }

    /**
     * "has many" relation to `user_role` table
     * via `user_id` field.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function userRole()
    {
        return $this->hasMany(\App\Models\UserRole::class, 'user_id');
    }

}
